Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,8 +17,8 @@ jobs:
       - name: Greeting
         run: echo "Hello, world!"
 
-      - name: Simulate an error
-        run: echo "About to fail" ; exit 1
+#       - name: Simulate an error
+#         run: echo "About to fail" ; exit 1
 
       - name: Another greeting
         run: echo "Hello, world!"
